### ISSUE TITLE
Wrong type definition

### ISSUE THREAD

**Issue by jcalderonzumba** [agiliumtrade-ai/metaapi-node.js-sdk#11]
Hi,

According to https://github.com/agiliumtrade-ai/metaapi-node.js-sdk/blob/11f16440a7a2a9f3115ecc277358796a017efdeb/lib/metaApi/historyStorage.es6#L52

The type definition found at:

https://github.com/agiliumtrade-ai/metaapi-node.js-sdk/blob/d6acec423ea5a8015bfc94ba964a7aecbf6f74dc/lib/metaApi/historyStorage.d.ts#L41

Should be async with `Promise<Date>;`

**Comment by RomanKisilenko** [comment]
This issue seems to be fixed and will be released soon.
