### ISSUE TITLE
onSynchronizationStarted problem

### ISSUE THREAD

**Issue by Pew0h** [agiliumtrade-ai/metaapi-node.js-sdk#12]
Hello ! I have a little problem of Synchronization.

Sometimes I can get this type of response after using await connection.waitSynchronized() :
event onSynchronizationStarted is taking more than 1 second to process
event onSynchronizationStarted finished in 16 seconds

OR I can receive an error : 
Time out waiting for MetaApi to syncrhonoze to metaTrader account ...., syncrhonization id undefined

Any solution please ?

**Comment by RomanKisilenko** [comment]
Update: onSynchronizationStarted can take some time to be processed in SDK, this is OK at this point.
