### ISSUE TITLE
Timed out waiting for account to connect to the broker

### ISSUE THREAD

**Issue by ibeallc** [agiliumtrade-ai/metaapi-node.js-sdk#2]
When i run the example I'm getting this error help

**Comment by RomanKisilenko** [comment]
Hello, please send me your email address via online chat on our website so that we can look into your MetaTrader account settings and advise how to fix it.

**Comment by RomanKisilenko** [comment]
Hello, please send me your email address via online chat on our website so that we can look into your MetaTrader account settings and advise how to fix it. Please also mention your MetaTrader account id in your message (you can find it on https://app.metaapi.cloud/accounts page).

**Comment by RomanKisilenko** [comment]
Hello, please send me your email address via online chat on our website so that we can look into your MetaTrader account settings and advise how to fix it. Please also mention your MetaTrader account id in your message (you can find it on https://app.metaapi.cloud/accounts page).

**Comment by RomanKisilenko** [comment]
Hello, please send me your email address via online chat on our website so that we can look into your MetaTrader account settings and advise how to fix it. Please also mention your MetaTrader account id in your message (you can find it on https://app.metaapi.cloud/accounts page).

**Comment by RomanKisilenko** [comment]
Hello, please send me your email address via online chat on our website so that we can look into your MetaTrader account settings and advise how to fix it. Please also mention your MetaTrader account id in your message (you can find it on https://app.metaapi.cloud/accounts page).

**Comment by RomanKisilenko** [comment]
Hello, please send me your email address via online chat on our website so that we can look into your MetaTrader account settings and advise how to fix it. Please also mention your MetaTrader account id in your message (you can find it on https://app.metaapi.cloud/accounts page).

**Comment by RomanKisilenko** [comment]
Hello, please send me your email address via online chat on our website so that we can look into your MetaTrader account settings and advise how to fix it. Please also mention your MetaTrader account id in your message (you can find it on https://app.metaapi.cloud/accounts page).

**Comment by RomanKisilenko** [comment]
Hello, please send me your email address via online chat on our website so that we can look into your MetaTrader account settings and advise how to fix it. Please also mention your MetaTrader account id in your message (you can find it on https://app.metaapi.cloud/accounts page).

**Comment by RomanKisilenko** [comment]
Hello, please send me your email address via online chat on our website so that we can look into your MetaTrader account settings and advise how to fix it. Please also mention your MetaTrader account id in your message (you can find it on https://app.metaapi.cloud/accounts page).

**Comment by ibeallc** [comment]
This issue is fixed that change the demo account correctly. Thank u
