### ISSUE TITLE
subscribeToMarketData function TypeError

### ISSUE THREAD

**Issue by whale-watching** [agiliumtrade-ai/metaapi-node.js-sdk#20]
I have met like Error in using Query contract specifications and quotes via RPC API.
![image](https://user-images.githubusercontent.com/93808977/195994738-0b4420d9-9228-454f-a2cf-26a836f8ee3b.png)
Please let me know How can I solve this problem.

**Comment by RomanKisilenko** [comment]
Hello, RPC API does not implement the subscribeToMarketData method. This method is only available in real-time streaming API.

**Comment by whale-watching** [comment]
Got it
