### ISSUE TITLE
Typings Errors on Typescript

### ISSUE THREAD

**Issue by fatihaziz** [agiliumtrade-ai/metaapi-node.js-sdk#21]
![image](https://user-images.githubusercontent.com/23287658/197863272-f5153e02-84b1-4e37-93b2-cf465765f576.png)
1. cannot find name "UserLogListener", on node_modules/metaapi.cloud-copyfactory-sdk/dist/clients/copyFactory/trading.client.d.ts:111:37
2. node_modules/metaapi.cloud-copyfactory-sdk/dist/clients/copyFactory/trading.client.d.ts:117:49 - error TS1183: An implementation cannot be declared in ambient contexts.
3. node_modules/metaapi.cloud-copyfactory-sdk/dist/clients/copyFactory/trading.client.d.ts:118:10 - error TS2339: Property '_userLogListenerManager' does not exist on type 'TradingClient'.
4. RpcMetaApiConnection.getSymbols() does'nt exist on version ^20, even though its exist on version 19.7.7.

i can use skipLibCheck to fix those issue regarding metaapi typings errors, but i cannot get the result i want.

## Versions:
OS: Windows 11
Typescript: TS4.7
NodeJS: 16.17.0
Module: metaapi-node.js-sdk@20.2.0

**Comment by fatihaziz** [comment]
meanwhile, i will try to modify and fix the package on my local.

**Comment by fatihaziz** [comment]
found it,
![image](https://user-images.githubusercontent.com/23287658/197871799-f7784b7a-ff1e-4e4f-b75f-c10abd511214.png)

the library typing mistakenly returning `RpcMetaApiConnection` which should be `RpcMetaApiConnectionInstance`
fixes on: https://github.com/agiliumtrade-ai/metaapi-node.js-sdk/pull/22

**Comment by fatihaziz** [comment]
Sorry, I might don't know if it's intentional. But it fixes my side.
Maybe just forgot to add some methods into `RpcMetaApiConnection` like getSymbols(), 
why I do this? Because the documentation (https://github.com/agiliumtrade-ai/metaapi-node.js-sdk/blob/master/docs/metaApi/rpcApi.md) say:
```
//...

// read symbols available
console.log(await connection.getSymbols());

//...
```

**Comment by fatihaziz** [comment]
Also, for errors from `node_modules/metaapi.cloud-copyfactory-sdk`
on my side, I decide to remove it, and not exporting it.
Maybe, it's better to tell user to install `metaapi.cloud-copyfactory-sdk` independently instead of `metaapi-node.js-sdk` requiring it and export the module here.

For example:

### Copyfactory SDK Installation
to use copyfactory sdk you need to install both:
`npm i metaapi-node.js-sdk metaapi.cloud-copyfactory-sdk`

**Comment by RomanKisilenko** [comment]
These were fixed in the latest SDK. Thank you for reporting the issue.

**Comment by fatihaziz** [comment]
Hello, i have check it. it seems there are errors.
![image](https://user-images.githubusercontent.com/23287658/199459288-9af6aaff-4199-48c4-8d24-c46f46a34201.png)

there is much missing types here:
1. rpcMetaApiConnectionInstance.d.ts, missing `MetaApiConnectionInstance` and `MetaApiConnectionInstance`
2. metaApiConnectionInstance.d.ts, missing `MetaApiConnection`
3. metatraderAccountReplica.d.ts, incorrect import, need to remove `MetatraderAccountReplica` 
4. connectionRegistry.d.ts, missing `RpcMetaApiConnection`

**Comment by fatihaziz** [comment]
![image](https://user-images.githubusercontent.com/23287658/199460765-e5042c90-971a-4ca0-b21a-09bb5fcb9bc7.png)
when i manually import them on node_modules, it fixed and run normally.

Thank you for your help anyway

**Comment by RomanKisilenko** [comment]
Hello, we've released another SDK update to address this issue. Please check on your side and let us know if you still experience any issue.

**Comment by fatihaziz** [comment]
It's fixed, thank you! 👏
