### ISSUE TITLE
ORDER_REASON_UNKNOWN should be ORDER_REASON_SL

### ISSUE THREAD

**Issue by devcryp** [agiliumtrade-ai/metaapi-node.js-sdk#24]
I am sending in an order with a stop loss. When the stop loss is triggered a new order is created with ORDER_REASON_UNKNOWN. In the brokerComment it says [sl], so I know it is the stop loss.

Order response
` id: '79962096',
  type: 'ORDER_TYPE_SELL',
  state: 'ORDER_STATE_FILLED',
  symbol: 'GOLD',
  magic: 0,
  time: 2022-10-28T07:13:44.000Z,
  doneTime: 2022-10-28T07:13:44.000Z,
  openPrice: 1655.37,
  currentPrice: 1652.99,
  accountCurrencyExchangeRate: 1,
  stopLoss: 1653,
  takeProfit: 1657,
  volume: 0.01,
  currentVolume: 0,
  positionId: '79962096',
  platform: 'mt4',
  reason: 'ORDER_REASON_UNKNOWN',
  fillingMode: 'ORDER_FILLING_FOK',
  expirationType: 'ORDER_TIME_SPECIFIED',
  comment: 'comment',
  brokerComment: 'comment[sl]',
  brokerTime: '2022-10-28 10:13:44.000',
  doneBrokerTime: '2022-10-28 10:13:44.000',
  updateSequenceNumber: 1666941224000005`

I would expect to receive ORDER_REASON_SL under reason as specified in the docs.
https://www.mql5.com/en/docs/constants/tradingconstants/orderproperties#enum_order_reason

Edit1: I am using mt4 with fxpro with socket stream api
Edit2: for every order, also simple market order, I am receiving ORDER_REASON_UNKNOWN

**Comment by RomanKisilenko** [comment]
Hello, MT4 does not support retrieving order reasons, thus you get the value above.
