### ISSUE TITLE
Stream multiple timeframes simultaneously using await connection.subscribeToMarketData

### ISSUE THREAD

**Issue by devcryp** [agiliumtrade-ai/metaapi-node.js-sdk#25]
Is it possible to subscribe to multiple candle timeframes using connection.subscribeToMarketData() ?

I tried 

```
await connection.subscribeToMarketData('GOLD', [{ type: 'candles', timeframe: '1m', intervalInMilliseconds: 500 }]);
await connection.subscribeToMarketData('GOLD', [{ type: 'candles', timeframe: '5m', intervalInMilliseconds: 500 }]);
```

and 

```
await connection.subscribeToMarketData('GOLD', [{ type: 'candles', timeframe: '1m', intervalInMilliseconds: 500 }, { type: 'candles', timeframe: '5m', intervalInMilliseconds: 500 }])
```

But both don't return desired result. Please let me know, thanks!

**Comment by devcryp** [comment]
Ok, it seems the first way is the way to go. But it was not working because I called subscribeToMarketData too soon after calling:

`await connection.unsubscribeFromMarketData('GOLD');`	

`await connection.subscribeToMarketData('GOLD', [{ type: 'candles', timeframe: '1m', intervalInMilliseconds: 500 }]);`
`await connection.subscribeToMarketData('GOLD', [{ type: 'candles', timeframe: '5m', intervalInMilliseconds: 500 }]);`

I was using await on unsubscribeFromMarketData() so I would expect I can continue right away. Now I am using a 5000ms delay between them and it works as expected. 

Can anyone explain why this is the case?

**Comment by RomanKisilenko** [comment]
Hello, this can be caused by some sort of race condition. You should not unsubscribe from market data stream just to subscribe to it again immediately. We will check if we can improve this on server side, however this is not a bug in SDK.
