### ISSUE TITLE
Is it possible to only receive completed candles through onCandlesUpdated() ?

### ISSUE THREAD

**Issue by devcryp** [agiliumtrade-ai/metaapi-node.js-sdk#26]
I am looking for the possibility to only receive updates about completed candles instead of receiving every price update. Is this possible and how?

`onCandlesUpdated()`

Thank you

**Comment by RomanKisilenko** [comment]
Please check this code example https://github.com/agiliumtrade-ai/metaapi-node.js-sdk/tree/master/examples/streamQuotes

If you do not need quote updates then simply do not add corresponding method to your listener.
