### ISSUE TITLE
request library is fully deprecated

### ISSUE THREAD

**Issue by Sinderella** [agiliumtrade-ai/metaapi-node.js-sdk#30]
According to their [repo](https://github.com/request/request), the library is fully deprecated, and there seems to be some notable security issues [here](https://github.com/request/request/issues?q=is%3Aissue+is%3Aopen+security).

Probably consider migrating to a different HTTP client library?

**Comment by RomanKisilenko** [comment]
request library has everything we need and I we do not use any vulnerable feature. We can consider upgrading qs version or replacing request with something else.

**Comment by RomanKisilenko** [comment]
We've migrated to a different http client library in a future version which will be released soon.
