### ISSUE TITLE
Timed out waiting for MetaApi to synchronize to MetaTrader account

### ISSUE THREAD

**Issue by ljs19923** [agiliumtrade-ai/metaapi-node.js-sdk#31]
Hey, Im trying to connect myself to one MT4 demo account with my broker, from the metaapi-node.js-sdk but I got this error :

Timed out waiting for MetaApi to synchronize to MetaTrader account.

If someone have an idea? Thanks

`console.info("Meta synchronization..");
  try {
    // Add test MetaTrader account
    let accounts = await api.metatraderAccountApi.getAccounts();
    let account = accounts.find(
      (a) => a.login === login && a.type.startsWith("cloud")
    );
    if (!account) {
      console.log("Adding MT4 account to MetaApi");
      account = await api.metatraderAccountApi.createAccount({
        name: "Test account",
        type: "cloud",
        login: login,
        password: password,
        server: serverName,
        platform: "mt4",
        magic: 1000,
      });
    } else {
      console.log("MT4 account already added to MetaApi");
    }

    // wait until account is deployed and connected to broker
    console.log("Deploying account");
    await account.deploy();
    console.log(
      "Waiting for API server to connect to broker (may take couple of minutes)"
    );
    await account.waitConnected();

    // connect to MetaApi API
    let connection = account.getRPCConnection();
    await connection.connect();

    // wait until terminal state synchronized to the local state
    console.log(
      "Waiting for SDK to synchronize to terminal state (may take some time depending on your history size)"
    );

    // IM BLOCKED AT THIS LINE
    await connection.waitSynchronized();

    // invoke RPC API (replace ticket numbers with actual ticket numbers which exist in your MT account)
    console.log("Testing MetaAPI RPC API");
    console.log(
      "account information:",
      await connection.getAccountInformation()
    );
    console.log("positions:", await connection.getPositions());`

**Comment by RomanKisilenko** [comment]
I can see on our online chat that you reported that you figured it out how to make your code working. Please reopen the GitHub issue or contact us via online chat if you still experience this issue.
