### ISSUE TITLE
The function unsubscribeFromMarketData looks like is not working

### ISSUE THREAD

**Issue by esepeasodegabi** [agiliumtrade-ai/metaapi-node.js-sdk#33]
this function has two parameters (symbol: string, subscriptions: MarketDataUnsubscription)
In documentation "subscriptions" is an Array, but in class StreamingMetaApiConnectionInstance is a single MarketDataUnsubscription.

When set a single object fails with this error:
 !subscriptions.find(s2 => s.type === s2.type));

**Comment by RomanKisilenko** [comment]
Thank you for bug report. This is fixed now in the 20.10.2 release.
