### ISSUE TITLE
Enable MetaStats API

### ISSUE THREAD

**Issue by moku23** [agiliumtrade-ai/metaapi-node.js-sdk#38]
I've read the notice about enabling MetaStats API now disabled by default.
I was looking for about any documentation but nothing found.
This doc have an error: [EnableMetaStats](https://metaapi.cloud/docs/provisioning/api/account/enableMetaStatsHourlyTarification/)

In which API call I need to enable MetaStats boolean value? which is the name of property?
Thanks for explanation

**Comment by RomanKisilenko** [comment]
Hello, please check https://metaapi.cloud/docs/provisioning/api/account/createAccount/, metastatsApiEnabled field.
