### ISSUE TITLE
Delay getting current pending orders.

### ISSUE THREAD

**Issue by mohammedalrawi1** [agiliumtrade-ai/metaapi-node.js-sdk#39]
I have tried both sockets and RPCAPI with node.js to retrieve the current open pending orders, but regardless of the method used, I consistently encounter a delay of approximately 1 minute. Additionally, I made an effort to synchronize the connection before each request, but the issue remains unchanged.
Any help? Please.

**Comment by MunizMat** [comment]
Unfortunately I am facing the same issue when trying to establish a websocket connection...

**Comment by RomanKisilenko** [comment]
Thank you for reporting this. We can not reproduce this on our side. 

Since this is a support question and not related to SDK please contact support via online chat to get individual assistance on the matter.
