### ISSUE TITLE
Bug. Information about Account margin didn't update

### ISSUE THREAD

**Issue by RuslanDen** [agiliumtrade-ai/metaapi-node.js-sdk#4]
Hello.

If I try to update account information in timeout function:

```
const connection = await metaAccount.connect();
await connection.waitSynchronized();

console.log(connection.terminalState.accountInformation)
```

Fields: margin,  freeMargin,  marginLevel didn't update, but other field updated

**Comment by RomanKisilenko** [comment]
Thank you for reporting this. We will be working on a fix soon.

**Comment by RomanKisilenko** [comment]
Hello, we fixed this issue last week and going to release the fix in the next MetaApi update in the end of this week.

**Comment by RomanKisilenko** [comment]
This change is now live in the latest SDK 11.0.0. Please test. I'll be closing this ticket but feel free to reopen it if needed.
