### ISSUE TITLE
MetatraderSymbolSpecification response model is missing 'Path' property

### ISSUE THREAD

**Issue by mikejlachlan** [agiliumtrade-ai/metaapi-node.js-sdk#40]
Hey Mate,

https://metaapi.cloud/docs/client/models/metatraderSymbolSpecification/ has a 'Path' property listed in the Response model however there is no 'Path' property being returned in the response. 

Can this pleased be fixed and returned in the response as per the response schema.

**Comment by RomanKisilenko** [comment]
Hello, please let us know which account type you are looking into? MT4 G1 or MT4 G2?

**Comment by RomanKisilenko** [comment]
I can see the path property is present for MT5 G1, MT5 G2, MT4 G1.

**Comment by RomanKisilenko** [comment]
We've also added this property to MT4 G2. It will be available in the next release in about a week.
