### ISSUE TITLE
There are no replicas deployed yet. Please make sure at least one of the replicas is deployed.'

### ISSUE THREAD

**Issue by moku23** [agiliumtrade-ai/metaapi-node.js-sdk#41]
Hello, 
from Today I'm getting this error:
`There are no replicas deployed yet. Please make sure at least one of the replicas is deployed.'`

 using on:
`metaStats.getAccountTrades(userId, start_date, end_date);`

**Comment by RomanKisilenko** [comment]
This means that you are trying to access an account which is not deployed and no replicas of this account are deployed either. You need to deploy the account to fix this issue.
