### ISSUE TITLE
Create stop limit buy order order type is not supported

### ISSUE THREAD

**Issue by enzoferey** [agiliumtrade-ai/metaapi-node.js-sdk#45]
Hi!

When trying to call `createStopLimitBuyOrder` the API answers back with the string code `ERR_ORDER_TYPE_NOT_SUPPORTED`.

Looking at the [docs](https://metaapi.cloud/docs/client/models/metatraderTrade/#order_type_buy_stop_limit-or-order_type_sell_stop_limit) and [code](https://github.com/agiliumtrade-ai/metaapi-node.js-sdk/blob/985153184c60866fbf59ac420b0c94b0c3ecd102/lib/metaApi/metaApiConnectionInstance.es6#L261) it seems the string is correct.

Maybe, do demo accounts have some kind of restriction in order types?

Same happens with `createStopLimitSellOrder` by the way.

Thanks.

**Comment by RomanKisilenko** [comment]
Do you use MT4 or MT5 account? Is your account deployed on G1 or on G2 infrastructure?

**Comment by enzoferey** [comment]
We have an MT4 account on the `ICMarkets-Demo03` server and the type is `cloud-g2`. Does that answer about infrastructure? Not sure if it's the same G1/G2 we are talking about.

**Comment by RomanKisilenko** [comment]
MT4 platform does not support stop limit orders.

**Comment by enzoferey** [comment]
@RomanKisilenko thanks for confirmation 👍🏻
