### ISSUE TITLE
Question more than an issue

### ISSUE THREAD

**Issue by jcalderonzumba** [agiliumtrade-ai/metaapi-node.js-sdk#5]
Do you have plans to migrate this SDK to typescript or to provide at least typings?

I am a client of your service and have my trading bot running in nodejs typescript and it would help me a lot if I had typings.

**Comment by RomanKisilenko** [comment]
Thank you for the question.

We have plans to provide typings in future. Most likely we will work on the typings in the end on May 2021.

**Comment by RomanKisilenko** [comment]
It seems like we have to reschedule this feature to be implemented approximately in July.

**Comment by RomanKisilenko** [comment]
It seems like we have to postpone this for more time since we are working on SDK tasks which are of much higher priority now. Hopefully we can implement the typings in Sep or Oct.

**Comment by RomanKisilenko** [comment]
Btw, anyone who is interested can apply to contribute this feature. We will support you with consultations if you are willing to take this task.

**Comment by RomanKisilenko** [comment]
We've processed this task and there are now typings available in the newest SDK release.
