### ISSUE TITLE
Error on the usage of async for HistoryStorage

### ISSUE THREAD

**Issue by jcalderonzumba** [agiliumtrade-ai/metaapi-node.js-sdk#6]
https://github.com/agiliumtrade-ai/metaapi-node.js-sdk/blob/4487367ff75c0d518ded6a0936e5cbd74368a7d9/lib/metaApi/metaApiConnection.es6#L454

https://github.com/agiliumtrade-ai/metaapi-node.js-sdk/blob/4487367ff75c0d518ded6a0936e5cbd74368a7d9/lib/metaApi/metaApiConnection.es6#L458

I am implementing a HistoryStorage for Database but I get errors and I believe it is because of the line shown above.

When working with async for the proper access to  `...getTime()` you need to change it to

```js 
(await this._historyStorage.lastHistoryOrderTime(instanceIndex)).getTime()
(await this._historyStorage.lastDealTime(instanceIndex)).getTime() 
``` 

So that it first resolves the promise with the await and then you access the object the promise returns.

I am not submitting a PR because I have no time to include testing, but I would appreciate fixing it whenever you can please so that I can implement my DatabaseHistoryStorage.

**Comment by RomanKisilenko** [comment]
Thank you for reporting this, we resolved it in master.
