### ISSUE TITLE
OHLC data

### ISSUE THREAD

**Issue by mahmutoktay** [agiliumtrade-ai/metaapi-node.js-sdk#7]
Can i get ohlc historical data?

**Comment by RomanKisilenko** [comment]
This feature is not available yet. I'm not sure yet about when exactly it will be added. Approximate estimate is that we will be able to add it somewhere in May for G1 accounts.

**Comment by mahmutoktay** [comment]
I saw the historical candle title in the documents on metaapi.cloud, this is good news.  How can I do this in the node library.  thanks

https://metaapi.cloud/docs/client/restApi/api/retrieveMarketData/readHistoricalCandles/

**Comment by RomanKisilenko** [comment]
We released this feature today. You can check this code sample on how to use it from SDK: https://github.com/agiliumtrade-ai/metaapi-node.js-sdk/tree/master/examples/retrieveHistoricalMarketData. 

Please note that this example can be executed using SDK version available from master branch only. We did not release it yet. We plan to release it soon, probably in a week or two. For now you can build the package from master branch if you need an SDK to access the market data. You can also easily access the market data API via REST API without using SDK.

**Comment by RomanKisilenko** [comment]
I'm closing this issue as completed now. Feel free to contact us via online chat if you'll need assistance using the feature.
