### ISSUE TITLE
How to avoid use of `fs` on cloud envs?

### ISSUE THREAD

**Issue by codinsonn** [agiliumtrade-ai/metaapi-node.js-sdk#8]
Is there a way to disable use of `fs` and / or `fs-extra` somehow?
Not all runtimes have editable filesystems, e.g. cloud functions or vercel / AWS lambda's

For example, this is a screenshot from one of many failed calls to one of [Vercel](https://vercel.com/)'s NextJS [API routes](https://nextjs.org/docs/api-routes/introduction)

<img width="979" alt="Screenshot 2021-08-22 at 11 36 48" src="https://user-images.githubusercontent.com/5967956/130350344-47d5616b-c735-447b-bbdd-515108229bf7.png">

Perhaps there is an option to import from `metaapi.cloud-sdk/serverless` or something like that?
(If not available yet, could be a great improvement)

I know I can attempt to use the socket or REST api's instead, which should avoid any edits to files on my or vercel's side of things, but it would be great if this was an option in the node-js SDK as well.

**Comment by RomanKisilenko** [comment]
Hello, you can supply a custom history storage like this one: https://gist.github.com/RomanKisilenko/e00c247fa8bf8caf35a750e842de40c1

Feel free to reopen the issue if this does not resolve the problem for you.

**Comment by codinsonn** [comment]
@RomanKisilenko This seems to have solved the issue, thanks!
